export const STATIC_SUBJECTS = [
    "COMPUTER AIDED ENGINEERING GRAPHICS-2",
    "BASIC ELECTRONICS & COMMUNICATION ENGINEERING",
    "PROGRAMMING FUNDAMENTALS",
    "AS SELECTED",
    "MATHEMATICS-I",
    "WEB DESIGNING"
];
